apiVersion: v1
kind: Pod
metadata:
  labels:
    app: db
  name: db
spec:
  containers:
  - env:
    - name: POSTGRESQL_USER
      value: user
    - name: POSTGRESQL_PASSWORD
      value: pass
    - name: POSTGRESQL_DATABASE
      value: db
    image: 345280441424.dkr.ecr.ap-south-1.amazonaws.com/ark_postgres:latest
    imagePullPolicy: Always
    name: db
    ports:
    - containerPort: 3306
      name: dbport
      protocol: TCP
  hostname: db
  imagePullSecrets:
  - name: aws-arkcase-pull
