#!/bin/bash
set -euo pipefail

timestamp() {
	/usr/bin/date -Ins -u
}

say() {
	echo -e "$(timestamp): ${@}"
}

fail() {
	say "${@}" 1>&2
	exit ${EXIT_CODE:-1}
}

# Update the SSL stuff
[ -v SSL_DIR ] || export SSL_DIR="/.ssl"
acme-init

exec "container-entrypoint" "${@}"
